### ISSUE TITLE
study good card page with mock data

### ISSUE THREAD

**Issue by javaskrskr** [kenwCoding/good_card_frontend#8]
### TODO
- [ ] 4 buttons: Browse, Game, Listen, Test, as studt options
- [ ] Show Stats: Total card count, total learned count, total starred count
- [ ] Card component: Title + its meanings
- [ ] Mock data, around 50?

### TBD
- [ ] - (Add new cards)
- [ ] (Change setting of studying options)
- [ ] (Hard press to edit, swipe right to hide / show transparent, swipe left to super-mark) >>> animation?

<img width="738" alt="image" src="https://user-images.githubusercontent.com/86917071/219761801-8c87e5b2-9b8e-4634-8d11-16136d7f00f9.png">
